spacelift-io/user-documentation

docs/concepts/policy/approval-policy.md
=> Fix bogus policy

docs/vendors/terraform/README.md
Flesh Terraform landing page out
=> Flesh Terraform landing page out

docs/integrations/source-control/github.md
We now require PR reviews in order to allow runs to be triggered when PRs are approved.
=> Add new required event to GitHub integration

docs/concepts/vcs-agent-pools.md
Document proxy support by the VCS Agent
=> Document proxy support by the VCS Agent

docs/integrations/source-control/azure-devops.md, docs/integrations/source-control/bitbucket-cloud.md, docs/integrations/source-control/bitbucket-datacenter-server.md, docs/integrations/source-control/gitlab.md
Document the lack of support for Azure DevOps Server by the VCS Agent
=> Document the lack of support for Azure DevOps Server by the VCS Agent

requirements.txt
Bump Material version to 8.5.1
=> Bump Material version to 8.5.1

docs/integrations/source-control/azure-devops.md
Remove the section about Azure DevOps Server until it has been fully tested.
Relates to #55.
=> Remove the section about Azure DevOps Server until it has been fully tested

mkdocs.yaml
Enable linked tabs
Preview: https://spacelift-user-documentation-pr-60.onrender.com/vendors/terraform/cdktf.html
=> Enable linked tabs

docs/integrations/source-control/github.md
Minor improvement to the GitHub page menu structure for clarity.
Before:
After:
=> Minor improvement to the GitHub page menu structure

docs/vendors/terraform/terragrunt.md
=> Fix Terragrunt copy

docs/concepts/configuration/runtime-configuration/runtime-yaml-reference.md
Clarify where the runtime configuration file should be located
=> Clarify where the runtime configuration file should be located

docs/concepts/vcs-agent-pools.md
Document the `NO_PROXY` env var available to the VCS Agent.
=> Document NO_PROXY

docs/concepts/stack/README.md
Add clarification about canceling runs and stack state
=> Add clarification about canceling runs and stack state

.gitignore, docs/concepts/run/proposed.md, docs/concepts/run/test-case.md, docs/concepts/run/tracked.md
=> Document skipping phases using environment variables

docs/integrations/cloud-providers/aws.md
I've added an example of how to use a `for_each` block along with the `spacelift_aws_integration_attachment_external_id` data source to generate the trust relationship for attaching a single integration to multiple stacks.
=> Add example of multi-stack trust relationship

docs/integrations/source-control/azure-devops.md
- Added the "Pull request commented on" event to the list of service hooks required for Azure DevOps.
- Reformatted the list of events as a list to make it easier to find the required events.
=> Azure DevOps mention PR comment event

docs/concepts/configuration/environment.md
A customer asked that question earlier today during the support interaction and I realized we don't have that documented.
=> Document environment variable interpolation

docs/concepts/stack/scheduling.md, nav.yaml
Add scheduling and TTL documentation (beta)
=> Add scheduling and TTL documentation (beta)

docs/concepts/policy/terraform-plan-policy.md, docs/concepts/policy/trigger-policy.md
=> Document trigger policies for modules

docs/concepts/spaces/permissions.md, nav.yaml
=> Permission table poc

.markdownlint.yaml
=> Allow tags for videos

docs/concepts/stack/creating-a-stack.md, docs/concepts/stack/drift-detection.md, docs/concepts/stack/organizing-stacks.md, docs/concepts/stack/stack-settings.md
=> add vimeo links for stacks

docs/integrations/source-control/github.md
=> Document GitHub deployment environment override

docs/concepts/configuration/runtime-configuration/README.md, docs/concepts/configuration/runtime-configuration/runtime-yaml-reference.md, docs/concepts/stack/stack-settings.md
=> Document after-run hooks

docs/concepts/configuration/runtime-configuration/runtime-yaml-reference.md, docs/vendors/terraform/module-registry.md
Added docs on module test case dependencies.
=> Add docs for module test case ordering

docs/concepts/stack/stack-settings.md
=> Mention final state in after-run hooks

docs/concepts/vcs-agent-pools.md
Document VCS Agent debug information
=> Document VCS Agent debug information

docs/concepts/policy/git-push-policy.md
=> Add clarification about cancellable runs in push policy docs

docs/integrations/cloud-providers/oidc.md
Document caveat when using the OIDC Cloud Integration with AWS
=> Document caveat when using the OIDC Cloud Integration with AWS

docs/integrations/single-sign-on/README.md
=> Document SAML Bindings

docs/concepts/spaces/README.md, docs/concepts/spaces/access-control.md, docs/concepts/spaces/creating-a-space.md, docs/concepts/spaces/deleting-a-space.md, docs/concepts/spaces/migrating-out-of-the-legacy-space.md, docs/concepts/spaces/moving-a-space-or-an-entity.md, docs/concepts/spaces/structuring-your-spaces-tree.md
=> Misc. Spaces fixes

docs/integrations/source-control/github.md
=> Remove obsolete link

docs/concepts/policy/git-push-policy.md
Signed-off-by: Jakub Martin <kubam@spacelift.io>
=> Update push policy docs.

docs/concepts/stack/stack-settings.md
Update outdated information regarding env vars and phase hooks
Preview: https://spacelift-user-documentation-pr-106.onrender.com/concepts/stack/stack-settings.html#customizing-workflow
=> Update outdated information regarding env vars and phase hooks

docs/integrations/single-sign-on/README.md
Rename G Suite to Google Workspace
=> Rename G Suite to Google Workspace

docs/concepts/policy/git-push-policy.md
Signed-off-by: Jakub Martin <kubam@spacelift.io>
=> Update default push policy.

docs/concepts/policy/git-push-policy.md
=> Improve formatting of default push policy

docs/integrations/api.md
Update the API token validity duration
=> Update the API token validity duration

docs/integrations/single-sign-on/azure-ad-oidc-setup-guide.md, docs/integrations/single-sign-on/gitlab-oidc-setup-guide.md, docs/integrations/single-sign-on/okta-oidc-setup-guide.md, docs/integrations/single-sign-on/onelogin-oidc-setup-guide.md
=> Fix emojis

docs/concepts/configuration/environment.md
fixes a small typo on the mounted files section in the environment screen
=> fixes typo in the mounted files section of the environment doc

docs/vendors/terraform/README.md, docs/vendors/terraform/provider-registry.md, nav.yaml
=> Beta docs for the provider registry

docs/vendors/kubernetes/authenticating.md
Update the kubectl and Docker image section
=> Update the kubectl and Docker image section

.markdownlint.yaml, docs/integrations/cloud-providers/oidc.md
Updated the docs to make the subject examples more obvious, and added a link back to the standard claims section.
=> Improve the Azure OIDC federation subject examples

docs/vendors/terraform/provider-registry.md
=> Fix version management commands

docs/concepts/worker-pools.md
=> Add ARM64 link, plus some minor improvements

.github/workflows/deploy-to-environment.yaml, .pre-commit-config.yaml
=> Update CI/CD dependencies

docs/vendors/kubernetes/authenticating.md, docs/vendors/kubernetes/getting-started.md
Fix hook names for Kubernetes authentication. Fixes #127.
=> Fix hook names for Kubernetes authentication

CONTRIBUTING.md, requirements.txt
Update theme version to 8.5.11
=> Update theme version to 8.5.11

docs/concepts/policy/README.md, docs/concepts/policy/approval-policy.md, docs/concepts/policy/git-push-policy.md, docs/concepts/policy/login-policy.md, docs/concepts/policy/stack-access-policy.md, docs/concepts/policy/terraform-plan-policy.md, docs/concepts/policy/trigger-policy.md
Add links to the policy library
=> Add links to the policy library

docs/concepts/policy/run-initialization-policy.md, docs/concepts/policy/task-run-policy.md, docs/concepts/policy/terraform-plan-policy.md
=> Add missing aliases

overrides/main.html
=> Add GTM scripts

docs/integrations/slack.md
=> Fix typo on the Slack page

overrides/main.html
Remove gtag scripts as we switched to GTM and gtag is no more needed.
=> Remove gtag

docs/concepts/configuration/environment.md
Fix maximum size of mounted files
=> Fix maximum size of mounted files

docs/concepts/policy/terraform-plan-policy.md
=> Do not prettify JSON

docs/vendors/terraform/terragrunt.md
Adding docs about support of `TG_TF_REGISTRY_TOKEN`.
=> Add documentation about `TG_TF_REGISTRY_TOKEN` env var

docs/vendors/ansible/ansible-galaxy.md
Mention Ansible requirements file alternative extension support
=> Mention Ansible requirements file alternative extension support

CONTRIBUTING.md, docs/integrations/single-sign-on/README.md
=> SSO clarification

docs/vendors/terraform/state-management.md
Add Terraform state export section
=> Add Terraform state export section

docs/integrations/docker.md
=> Add container registry names where it makes sense to allowed registries

docs/concepts/worker-pools.md
=> Add AWS S3 and IOT core endpoint documentation links

docs/concepts/policy/terraform-plan-policy.md
=> Added soft scanning option to custom inputs example

.github/pull_request_template.md
Update PR template for Spacelift employee contributions
=> Update PR template for Spacelift employee contributions

docs/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.md
Document AWS IAM Identity Center SAML teams attribute mapping
Preview: https://spacelift-user-documentation-pr-153.onrender.com/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.html#assign-users-and-groups-to-the-application
=> Document AWS IAM Identity Center SAML teams attribute mapping

docs/integrations/audit-trail.md
Mention the Audit Trail endpoint reference implementation for AWS
=> Mention the Audit Trail endpoint reference implementation for AWS

docs/concepts/worker-pools.md
=> Mention what a worker is

docs/integrations/slack.md
=> Add documentation about slack access with login policies

docs/integrations/single-sign-on/README.md
Add Managed IdP vs SSO section
=> Add Managed IdP vs SSO section

docs/concepts/policy/notification-policy.md
Update Notification policy input data schema.
I understand that not every property will be available for every event but I think that we should cover what people could see.
=> Update Notification policy input data schema

.github/workflows/deploy-to-environment.yaml
=> Bump AWS configurer task to `v2`

docs/concepts/policy/login-policy.md
Mention that OPA string comparison is case-sensitive
=> Mention that OPA string comparison is case-sensitive

.vscode/extensions.json, docs/concepts/blueprint/README.md, markdown-link-check.json
=> Update blueprints doc with permission model

docs/concepts/policy/notification-policy.md
=> Mention the new notification policy changes in docs

docs/concepts/worker-pools.md
Clarify VCS agent configuration with private workers
Preview: https://spacelift-user-documentation-pr-177.onrender.com/concepts/worker-pools.html#vcs-agents
=> Clarify VCS agent configuration with private workers

docs/concepts/policy/notification-policy.md
=> Fix the input data for module version events

docs/concepts/worker-pools.md
Clarify that Docker needs to be running
=> Clarify that Docker needs to be running

docs/integrations/chatops/msteams.md, docs/integrations/chatops/slack.md, nav.yaml
=> Document MS Teams integration

docs/concepts/policy/notification-policy.md, docs/concepts/run/proposed.md, docs/concepts/run/tracked.md, docs/integrations/chatops/slack.md
=> Slack fixes

docs/concepts/run/README.md
=> Document run logs retention

docs/concepts/policy/run-initialization-policy.md, docs/concepts/policy/task-run-policy.md
=> Migration guide for deprecated init and task policies

docs/concepts/run/pull-request-comments.md
Clarify the policy type required
=> Clarify the policy type required

docs/vendors/terraform/module-registry.md
=> Add an example Dependabot configuration

overrides/main.html
Add Segment integration snippet
=> Add Segment integration snippet

docs/integrations/single-sign-on/README.md, docs/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.md, docs/integrations/single-sign-on/azure-ad-oidc-setup-guide.md, docs/integrations/single-sign-on/gitlab-oidc-setup-guide.md, docs/integrations/single-sign-on/okta-oidc-setup-guide.md, docs/integrations/single-sign-on/onelogin-oidc-setup-guide.md
Add callouts to recommend preparing backup credentials to the SSO installation guides.
=> Add callouts for SSO backup credentials

docs/concepts/blueprint/README.md
=> removes extra word

docs/concepts/run/README.md
=> Remove outdated sentence

docs/concepts/worker-pools.md
=> Update workpool configuration section

docs/product/migrating-to-spacelift.md, nav.yaml
Add the "Migrating to Spacelift" page
=> Add the Migrating to Spacelift page

docs/product/migrating-to-spacelift.md
Add TFC/TFE to Spacelift glossary
=> Add TFC/TFE to Spacelift glossary

docs/assets/css/extra.css, hooks/fetch_banner.py, mkdocs.yaml, overrides/partials/banner.html, overrides/partials/header.html
Adding a top banner for marketing purposes. Data will be re-fetched from WP on every rebuild.
=> add top banner with content from wordpress

docs/product/migrating-to-spacelift.md
Improve TFC/TFE to Spacelift glossary
=> Improve TFC/TFE to Spacelift glossary

.github/workflows/deploy-to-environment.yaml
=> wire-up repository var

.github/workflows/deploy-to-environment.yaml
=> fix passing env var

docs/concepts/policy/git-push-policy.md
=> Fix example policies syntax

docs/vendors/terraform/cdktf.md
=> Make the obvious more obvious

docs/assets/css/extra.css
=> fix hello banner z-index

docs/concepts/policy/git-push-policy.md
=> Fix Markdown syntax

docs/concepts/policy/notification-policy.md
=> fixes run & stack url in code snippet

docs/integrations/api.md
JSON content wasn't in the expandable box so I updated it to fit within the box
=> Updated expandable json content

docs/concepts/configuration/runtime-configuration/README.md
Listed the order of precendence for stack config settings 
=> stack config precedence

docs/concepts/blueprint/README.md
=> Add `secret` input type to Blueprints

docs/README.md
Add Ansible to Hello, Spacelift! intro paragraph.
=> Update README.md to include Ansible

nav.yaml
Add raw git link to navigation
=> Add raw git link to navigation

CONTRIBUTING.md
=> Update contribution guide for self-hosted

docs/self-hosted.md
- Fixed the broken link to the self-hosting docs.
- Added more detail about self-hosting, as well as how customers can contact us to try it out.
=> Improve self-hosting info page

.github/pull_request_template.md
Re-adding the preview step now that the Render preview has been re-enabled.
=> Re-add preview step to PR checklist

docs/product/support/README.md, nav.self-hosted.yaml
I've made some initial adjustments to the support page for self-hosted. It will probably still need more work, but I've tried to at least remove misleading things like the mention of different plans from self-hosted.
I've also removed the billing pages for now because they are heavily geared towards SaaS.
=> Adjust support page and remove billing for self-hosted

docs/product/support/README.md
Since the chat widget isn't available in self-hosted, mention the support email address.
=> Mention support email for self-hosted

docs/concepts/vcs-agent-pools.md
=> Add documentation related to vcs-agent debug mode

docs/concepts/policy/approval-policy.md
=> Fixed approval policy example typo

.github/pull_request_template.md
I've added some items to the PR checklist to make it obvious to contributors that there are two navigation files now, and changes may need to be made to both.
=> Update PR checklist to mention self-hosted nav

.github/workflows/deploy-to-environment.yaml, .github/workflows/self-hosted-release.yaml, docs/concepts/blueprint/README.md, docs/integrations/cloud-providers/oidc.md, docs/integrations/source-control/README.md, docs/integrations/source-control/bitbucket-datacenter-server.md, docs/product/security.md, docs/vendors/kubernetes/authenticating.md, docs/vendors/kubernetes/getting-started.md, docs/vendors/terraform/external-modules.md, scripts/remove-files-based-on-distribution.sh, scripts/render-build.sh
Depending on the context of the docs, certain pages don't make sense. I'm removing them so that they can't be accessed via a direct URL, and so that they don't appear in search results.
For now I'm taking the easy option of just deleting the irrelevant files before building the site. It's currently using a hard-coded list, although maybe we could base it on the nav file in future.
I also investigated [mkdocs-exclude-search](https://github.com/chrieke/mkdocs-exclude-search) and [mkdocs Material search exclusion](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-exclusion). What I found was that the `exclude-search` plugin excluded pretty much every page, not just ones that aren't linked in the nav, and I found that the search box disappeared after updating …
=> Exclude certain pages depending on whether docs are SaaS or Self-Hosted

overrides/partials/header.html, requirements.txt
Update Material for MkDocs to version 9.1.18
=> Update Material for MkDocs to version 9.1.18

docs/integrations/cloud-providers/oidc.md
=> Small changes to the OIDC vault integration

docs/integrations/cloud-providers/gcp.md
Recommending OIDC to be used for integrating GCP 
=> recommending oidc for gcp integrations

docs/concepts/stack/drift-detection.md, docs/concepts/stack/scheduling.md, docs/concepts/vcs-agent-pools.md, docs/concepts/worker-pools.md, docs/integrations/audit-trail.md, docs/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.md
=> updates to reflect enterprise features

docs/vendors/terraform/module-registry.md
=> Add documentation about module version bumping

docs/integrations/cloud-providers/oidc.md
This has happened twice so far so let's make it clear to everyone.
=> Add note about a typical OIDC error

docs/concepts/blueprint/README.md, docs/concepts/policy/approval-policy.md, docs/concepts/policy/notification-policy.md, docs/concepts/policy/push-policy/README.md, docs/concepts/policy/stack-access-policy.md, docs/concepts/stack/organizing-stacks.md, docs/product/administration/install.md, docs/product/disaster-continuity.md, docs/product/migrating-to-spacelift.md, docs/vendors/terraform/external-modules.md
minor copyedits
- [ X ] The commit history is clean and meaningful.
- [ X ] The pull request is opened against the `main` branch.
- [ X ] The pull request is no longer marked as a draft.
- [ X  ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- [ X ] You have updated the navigation files correctly:
- [ X ] No new pages have been added, or;
_Spacelift employees should request reviews from the …
=> minor copyedits

docs/concepts/stack/stack-dependencies.md
=> Clarify that Trigger policies are not deprecated

.github/pull_request_template.md
=> Fix GitHub PR template

docs/integrations/source-control/README.md, docs/product/administration/changelog.md, nav.self-hosted.yaml
=> Document v0.0.8 of self hosted

scripts/remove-files-based-on-distribution.sh
=> Don't remove Raw Git md page for SH

docs/product/administration/install.md
Updating the error message output if the AWS account ID can't be found to match the latest changes.
=> Updated self-hosted AWS error message

docs/product/support/README.md
Display Self-Hosted support information on the SaaS page for clarity
=> Display Self-Hosted support information on the SaaS page for clarity

docs/integrations/cloud-providers/aws.md
=> IAM-cross-account-hint

overrides/main.html
Added GTM `dataLayer.push` when user types into search. Debounce is `1000ms`.
=> Add dataLayer.push for search

docs/concepts/blueprint/README.md
=> fixed formatting of duration example

docs/concepts/policy/login-policy.md
=> single login policy tip

docs/self-hosted.md
Updated the "How to Try Self-Hosted" section to include a link to book a 15m alignment call.
=> Update info about how to try self-hosted

docs/integrations/source-control/github.md, overrides/main.html
updates GitHub docs to clarify the different install process
=> adds warning box to github docs

docs/integrations/single-sign-on/azure-ad-oidc-setup-guide.md
=> adds warning message to ADO doc regarding teams

docs/concepts/policy/README.md
=> Add policy backwards-compatibility notice.

docs/concepts/policy/push-policy/README.md
I've added an example push policy to compare branches and cancel proposed runs in queued state pointing to a specific branch.
=> Updated push policy docs to add an example for comparing branches

docs/concepts/policy/approval-policy.md, docs/concepts/run/proposed.md
=> Add documentation about proposed runs pending review.

docs/concepts/run/task.md
=> tip for tasks

docs/concepts/stack/stack-dependencies.md
As per our latest production release.
=> Update Stack Dependency access control docs

docs/concepts/stack/stack-settings.md
=> Add a tip about hooks to docs

docs/concepts/blueprint/README.md
Added documentation about using escape sequences when trying to generate Blueprint template bodies using the Terraform `templatefile` function. This can cause issues because both Blueprints and `templatefile` use similar template delimeters.
=> Document templatefile escaping for Blueprints

docs/concepts/spaces/access-control.md
I've updated the documentation section for the rule names of Space Access to align with the names in the Login Policy.
=> Updated policy rule names for Space Access Control

.github/workflows/deploy-to-environment.yaml, .github/workflows/qa.yaml, .github/workflows/self-hosted-release.yaml, docs/concepts/configuration/runtime-configuration/README.md, docs/concepts/policy/push-policy/run-external-dependencies.md, docs/integrations/docker.md, docs/vendors/terraform/provider-registry.md
=> Add information about different runner image flavors

docs/faq/README.md
Add "What counts a user?" FAQ entry.
=> Add "What counts a user?" FAQ entry

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: add self hosted v0.0.9 changelog

docs/concepts/policy/push-policy/README.md, docs/concepts/policy/trigger-policy.md
=> updated data inputs

docs/concepts/spacectl.md, nav.self-hosted.yaml, nav.yaml
I've added the information from the Spacelift GH repository under the Main Concepts in our documentation
=> Added spacectl docs under the main concepts

docs/integrations/api.md
=> removing note about postman

docs/integrations/audit-trail.md
=> information about failure retries

docs/concepts/stack/stack-dependencies.md
=> Add stack deps ref to self-hosted

docs/vendors/terraform/workflow-tool.md
=> Clarify responsibility for running 3rd party software

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: add self hosted v0.0.10 changelog

docs/concepts/user-management/README.md, docs/concepts/user-management/admin.md, docs/concepts/user-management/user.md
New user management will be generally available.
=> Make new user management generally available

docs/concepts/stack/stack-settings.md
=> Added details about magic labels

v0.0.10/index.html
This is updating the release snapshot created by Mike. Here's the PR to fix the source: https://github.com/spacelift-io/user-documentation/pull/377
=> fix: add missing workflow tool link

nav.self-hosted.yaml
We forgot to add this when creating the new release docs.
=> fix: add workflow tool page to Self-Hosted nav

docs/concepts/policy/push-policy/README.md
=> updating new default push policy

scripts/remove-files-based-on-distribution.sh
Remove user management pages from self-hosted 
=> Remove um screens from self hosted

docs/concepts/vcs-agent-pools.md
=> Add new VCS Agent (multi-arch) to docs

docs/concepts/policy/push-policy/README.md
=> updated default and data input

docs/concepts/policy/push-policy/README.md
=> Fix the default push policy

docs/concepts/stack/stack-settings.md
=> updated labels

docs/vendors/terraform/terraform-provider.md
=> Added information about creating Stack Dependencies to the provider docs

docs/concepts/policy/README.md
=> query to get version

docs/product/support/README.md
Fix installation link for slef-hosted
=> Update requirements link

docs/faq/README.md
=> adding tip regarding adblock

docs/vendors/terraform/module-registry.md
=> non admin keys must be defined in policy

docs/product/administration/install.md
In the install docs we indicate you can use an alias when the LB exists in the same account, but it's actually possible to setup an alias for a resource in a different account.
=> Correct Self-Hosted A record install docs

docs/vendors/terraform/terraform-provider.md
=> removes outdated arguments from provider docs

docs/integrations/observability/README.md, nav.self-hosted.yaml, nav.yaml
=> creates observability landing page

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: add self hosted v0.0.11 changelog

docs/vendors/terraform/terragrunt.md
=> refer back to native integration

docs/concepts/spaces/access-control.md, docs/vendors/terraform/module-registry.md
=> Accesscontrol

docs/legal/privacy.md
I've updated the Warsaw address.
=> Updated the GPDR related address

docs/vendors/ansible/reference.md
=> adding env var to ansible section

docs/vendors/terraform/external-modules.md
=> tip for common error

docs/concepts/policy/push-policy/README.md
=> updated tag driven push policy

docs/concepts/policy/notification-policy.md
=> Pull request notifications

docs/concepts/policy/push-policy/README.md, docs/concepts/run/README.md
This change briefly documents a new policy-based run prioritization functionality.
=> Policy-based run prioritization

docs/self-hosted.md
=> fix schedule demo link

docs/concepts/policy/push-policy/README.md
=> fix tag-driven module release policy

docs/integrations/cloud-providers/oidc/azure-oidc.md
OIDC federation works with user-assigned managed identities as well as with Apps. The configuration options are the same for both managed identities and apps, so I've just added a tip rather than altering the setup instructions.
=> Mention that OIDC federation can be used with managed identities

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: add self hosted v0.0.12 changelog

docs/concepts/policy/push-policy/README.md
=> Push policy stack locking

docs/vendors/kubernetes/workflow-tool.md
=> kubernetes typo

docs/concepts/blueprint/README.md
=> Add Blueprint docs, plus refresh schema

docs/concepts/policy/push-policy/README.md
=> Add MultiVCS to push policy

docs/concepts/run/README.md
=> information about limiting runs

docs/concepts/stack/stack-settings.md
=> MultiVCS - fix dead link

docs/concepts/worker-pools.md
Just adds some more details about how to set timeouts.
=> feat: add k8s native timeouts

docs/product/administration/install.md
=> Add note about new self-hosted config file field

docs/concepts/policy/push-policy/README.md
=> Add condition for proposed runs to start

docs/concepts/stack/stack-settings.md
=> Add the PR delta disable magic label

.vscode/settings.json, docs/faq/README.md
=> updated FAQ

docs/vendors/ansible/ansible-galaxy.md, docs/vendors/ansible/reference.md
Adding docs for a new feature.
=> Add info about overriding Ansible requirements.yml file location

docs/product/administration/changelog.md, nav.self-hosted.yaml, scripts/remove-files-based-on-distribution.sh
=> Docs for self-hosted v1.0.0

docs/concepts/worker-pools.md
I've added information on migrating from using the Docker-in-Docker Helm chart to our worker pool operator. I haven't added a step-by-step migration guide, but what I've tried to do is call out some important pieces of information to be aware of when migrating.
=> Add info on migrating from DinD to the operator

docs/concepts/worker-pools.md
=> Add a section about troubleshooting Kubernetes workers

docs/integrations/cloud-providers/oidc/gcp-oidc.md
=> updated tip

docs/concepts/stack/stack-settings.md
=> Add note about `feature:add_plan_pr_comment` label

docs/concepts/stack/stack-dependencies.md
=> message about cloudformation outputs

docs/concepts/stack/stack-dependencies.md
=> fixed wording on note

docs/concepts/stack/stack-dependencies.md
=> Add a note about Stack Dep Ref triggering logic

docs/integrations/source-control/github.md
=> remove message about deleting account data

docs/concepts/configuration/runtime-configuration/README.md
=> feat: add opentofu_version and terraform_workflow_tool to docs

docs/concepts/worker-pools.md
Follow up of https://github.com/spacelift-io/kube-workerpool-controller/pull/109
=> feat: add security context

docs/concepts/policy/push-policy/README.md
=> fixed for track conditions

docs/concepts/policy/push-policy/README.md
=> Update default push policy

docs/concepts/worker-pools.md
I've added a list of commands to run to get output to help us troubleshoot in the instance where a customer is unable to figure out why runs are failing / not starting themselves.
=> Add more troubleshooting info for run Pod failures

docs/concepts/blueprint/README.md
Blueprints support Terragrunt now. Let's add docs.
=> Add terragrunt examples for blueprints

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Documentation for Self Hosted release v1.1.0

requirements.txt
Currently the build fails - https://github.com/spacelift-io/user-documentation/actions/runs/8569091459/job/23484329516. 
The error seems to be correlated with the most recent commit they added - https://github.com/jimporter/mike/commit/ac7b2403cacb0a16892ce915478bac70bd7faf39
Let's pin to the version that succeeded during the last release.
https://github.com/jimporter/mike/commit/af47b9699aeeeea7f9ecea2631e1c9cfd92e06af
_Spacelift employees should request reviews from the relevant …
=> Pin Mike version

mkdocs.yaml
=> Currentyear

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Add docs for v1.1.0-hotfix.1

docs/product/administration/changelog.md, docs/product/administration/install.md, docs/vendors/terraform/terraform-provider.md
Waiting for: https://github.com/spacelift-io/user-documentation/pull/505
For self-hosted v1.2.0
=> Add changelog for selfhosted v1.2.0

docs/concepts/stack/stack-settings.md
=> Add well known secret masking

docs/concepts/policy/terraform-plan-policy.md
internal ref: https://spacelift-io.slack.com/archives/C03PKMZAMMW/p1715617660724169
=> Update terraform-plan-policy data input typo

docs/concepts/vcs-agent-pools.md
=> fix typo in vcs-agent-pools.md

docs/concepts/configuration/context.md
internal ref: https://spacelift-io.slack.com/archives/C05NTBP82KC/p1710521965931299?thread_ts=1710450631.684409&cid=C05NTBP82KC
=> Update context.md to add additional information about priorities

docs/integrations/chatops/slack.md
=> updated team data input information and expanded info

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Add changelog for SelfHosted v1.2.1

docs/concepts/configuration/runtime-configuration/README.md
Now, we can configure Terragrunt via `config.yml`.
=> Support configuring Terragrunt config via config.yml file

docs/concepts/worker-pools/kubernetes-workers.md
Documentation for https://github.com/spacelift-io/kube-workerpool-controller/pull/116
=> feat(CU-8694rub0t): add workerpool sidecar container doc

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
waiting for https://github.com/spacelift-io/self-hosted/pull/370
=> Add changelog for SelfHosted v1.3.0

docs/vendors/terraform/module-registry.md
Update module creation slug docs, to be consistence with current logic
=> Update module slug creation docs

docs/integrations/kubernetes/operator.md, nav.self-hosted.yaml, nav.yaml
=> Add K8s Operator docs

.editorconfig, hooks/move_index.py, mkdocs.yaml
This reverts commit 0644d0a5b2db6db78dddf21ac5b8ee8eabf5f1a1.
=> Revert "feat: move files so that we dont break links on accident"

docs/product/administration/install.md
=> Document custom database for self-hosted

docs/concepts/policy/push-policy/README.md, docs/concepts/stack/stack-settings.md
=> Pushpolicytip

docs/concepts/policy/notification-policy.md
Updates the notification policy documentation by adding the new "update PR comments in place" feature.
=> Updates the notification policy documentation by adding the new "update PR comments in place" feature.

docs/faq/README.md
=> updated feature request FAQ

docs/vendors/terraform/state-management.md
=> fix: empty state rollback warning modal

docs/concepts/blueprint/README.md
=> Add info on quotes around input vars

docs/concepts/policy/trigger-policy.md
=> add state history field in data input

docs/concepts/stack/stack-dependencies.md
=> Document removing reference output behaviour

docs/concepts/stack/stack-settings.md
=> Update stack-settings.md - add warning about project globs

docs/concepts/run/README.md
internal ref: https://spacelift-io.slack.com/archives/C059GJ3UC5U/p1722554463822869
=> Update README.md to add full list of potential run states

docs/concepts/blueprint/README.md
=> Update Blueprints README.md to add project_globs

docs/concepts/policy/login-policy.md
=> Update login-policy.md to mention api keys

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: add changelog for v2.0.0 of Self-Hosted

docs/concepts/stack/stack-settings.md
=> added tip for wrapping in parenthesis

docs/concepts/policy/notification-policy.md
Add run url to the notification policy input
=> Add run URL to input in documentation

docs/concepts/worker-pools/kubernetes-workers.md
=> Fix worker pool docs

docs/integrations/source-control/bitbucket-cloud.md
=> Update bitbucket-cloud.md to add bitbucket troubleshooting steps

docs/concepts/worker-pools/kubernetes-workers.md
Changes to support https://github.com/spacelift-io/spacelift-helm-charts/pull/71
=> feat(CU-8694n02d7): add docs for enabling prometheus metrics

docs/integrations/docker.md
This example actually didn't work. A kind customer of ours pointed it out. :) Thanks James.
=> Fix Dockerfile example

docs/concepts/spaces/structuring-your-spaces-tree.md
internal ref: https://spacelift-io.slack.com/archives/C04DN9U2S2F/p1724209640184099?thread_ts=1724208334.895539&cid=C04DN9U2S2F
=> Update structuring-your-spaces-tree.md to add note about inheritance

docs/concepts/configuration/runtime-configuration/README.md
internal ref: https://spacelift-io.slack.com/archives/C072EKK1UUQ/p1724348395910799
=> Update README.md add-example-complex-env-var-to-config-yml

docs/concepts/policy/README.md, docs/concepts/policy/approval-policy.md, docs/concepts/policy/login-policy.md, docs/concepts/policy/notification-policy.md, docs/concepts/policy/push-policy/README.md, docs/concepts/policy/terraform-plan-policy.md, docs/concepts/policy/trigger-policy.md
=> add rego.v1 note

docs/concepts/worker-pools/kubernetes-workers.md
=> Update kubernetes-workers.md tab for helm to display prometheus stuff

docs/concepts/spaces/structuring-your-spaces-tree.md, docs/vendors/terragrunt/reference.md
=> added information about registry token env var in terragrunt stacks

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Add changelog for Self-Hosted v2.1.0 release

docs/concepts/policy/approval-policy.md
internal ref: https://spacelift-io.slack.com/archives/C03HR007A4A/p1724791941747119
=> Update approval-policy.md to add information about stack dependencies

docs/concepts/worker-pools/kubernetes-workers.md
Added an info box to explain to readers that namespace of the controller and workers themselves do not impact functionality.
=> Added info box to Kubernetes Controller Docs

docs/concepts/worker-pools/kubernetes-workers.md
=> Update kubernetes-workers.md to include note about helm crd's limitation

docs/vendors/terragrunt/limitations.md
=> document usage of run_cmd

docs/faq/README.md
=> faq for feature request

docs/faq/README.md, docs/product/feature-requests.md
Use the custom domain for feature request gathering tool
=> Update featurebase url to point towards the custom domain

docs/concepts/policy/notification-policy.md
=> Update docs for the notification-policy: update PR comment feature

docs/integrations/cloud-providers/aws.md
internal ref: https://spacelift-io.slack.com/archives/C036ERF1VRU/p1726046978673069?thread_ts=1725923969.160549&cid=C036ERF1VRU
=> Update aws.md to include warning about sts for self hosted

docs/concepts/run/pull-request-comments.md
=> Update the pull request comments section

nav.self-hosted.yaml
Add SH bulk actions documentation - should be added after the next SH release (after 2.1.0)
=> Add bulk actions SH navigation link

docs/concepts/blueprint/README.md
We __always__ had this, we just completely forgot to document it.
=> feat(blueprint): document string extensions

docs/concepts/blueprint/README.md
=> fix: fix blueprint docs

docs/integrations/chatops/msteams.md
=> Update msteams.md about current connectors deprecation in msteams

docs/concepts/run/test-case.md
=> Update test-case.md to add note about adding cloud provider

docs/integrations/kubernetes/operator.md
=> Update operator.md to fix link pointing to config-operator

docs/integrations/cloud-providers/aws.md
=> Update aws.md add link on how to enable sts

docs/integrations/api.md, docs/vendors/terraform/module-registry.md
=> clearer notes and an example for renovate

docs/concepts/blueprint/README.md
=> fixing blueprint schema which was missing two commas

docs/concepts/policy/notification-policy.md
Notification policy: update PR comment, in place: remove info about supported VCS as all of them are supported now.
=> remove info about supported VCS as all of them are supported now

docs/vendors/ansible/reference.md
To be merged once feature is rolled out: https://github.com/spacelift-io/backend/pull/8017
=> feat: ansible colored output

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
We created a hotfix release to fix a couple of specific issues, but forgot to add the information to the changelog.
=> Add missing changelog for v2.1.1 of Self-Hosted

docs/vendors/kubernetes/getting-started.md
=> specify edge case of removal of deployments

docs/getting-started.md
=> Update getting-started.md to fix location information for the policies

docs/concepts/blueprint/README.md, docs/concepts/policy/README.md, docs/concepts/policy/push-policy/README.md, docs/concepts/run/task.md, docs/concepts/run/tracked.md, docs/concepts/stack/drift-detection.md, docs/concepts/stack/scheduling.md, docs/concepts/vcs-agent-pools.md, docs/concepts/worker-pools/README.md, docs/integrations/api.md, docs/integrations/audit-trail.md, docs/integrations/single-sign-on/README.md, docs/integrations/source-control/azure-devops.md, docs/integrations/source-control/bitbucket-cloud.md, docs/integrations/source-control/bitbucket-datacenter-server.md, docs/integrations/source-control/github.md, docs/integrations/source-control/gitlab.md, docs/integrations/webhooks.md, docs/product/notifications.md, docs/product/security/mfa.md, docs/vendors/terraform/module-registry.md, docs/vendors/terraform/provider-registry.md
=> updated feature call outs

docs/concepts/policy/login-policy.md
=> remove call out

docs/concepts/policy/push-policy/README.md
=> fix syntax

docs/concepts/spaces/access-control.md
=> clarifying ability to add comments to runs as a reader

CONTRIBUTING.md
=> updated instructions for correct branch

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
For the upcoming selfhosted release.
=> Changelog for SH v2.3.0

mkdocs.yaml
add copying icon for code blocks
=> add copying icon for code blocks Update mkdocs.yaml

docs/assets/css/custom.css, mkdocs.yaml
=> add dark theme

docs/concepts/policy/README.md
=> Update README.md to remove-edit-step-to-get-to-policy-workbench

docs/integrations/kubernetes/config-operator.md
More context here
https://spacelift-io.slack.com/archives/C06K7RN0CFJ/p1735836865194119
=> chore: remove beta mention for spacelift operator

docs/concepts/stack/stack-settings.md
=> Changed video for stack settings

docs/concepts/worker-pools/kubernetes-workers.md
This adds a new section into the k8s workerpool section that explains how to perform upgrade for versions with breaking changes.
=> doc(CU-8695egu2z): add k8s workerpool upgrade instructions

mkdocs.yaml
This is for updating the copyright year in the footer
=> This is for updating the copyright year in the footer

docs/concepts/stack/deleting-a-stack.md
=> Add OpenTofu command to "Stack Deletion" page

docs/integrations/teleport.md, markdown-link-check.json
Fixing dead URL links that were breaking the CI checks.
=> fix: dead url links

docs/integrations/single-sign-on/azure-ad-oidc-setup-guide.md
=> add warning about group size information

docs/concepts/blueprint/README.md
Add missing properties to Blueprint docs
=> Add missing properties to Blueprint docs

docs/concepts/stack/deleting-a-stack.md, docs/vendors/terragrunt/limitations.md
=> updating warnings and limitation about terragrunt support

docs/concepts/stack/stack-settings.md
=> Update stack-settings.md to add project globs example

docs/assets/css/custom.css
=> fix hubspot chat color-scheme

docs/integrations/teleport.md, docs/legal/archive/terms.md, docs/legal/dpa.md, docs/legal/privacy.md, nav.self-hosted.yaml, nav.yaml
=> legal updates

docs/concepts/run/run-promotion.md
=> fix: mention write permission in run promotion

docs/legal/privacy.md
=> updating address

docs/concepts/policy/trigger-policy.md
internal ref: https://spacelift-io.slack.com/archives/C036ERF1VRU/p1740437903043489
=> Update trigger-policy.md to add a note

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
New self-hosted release v2.5.0
=> feat: new self-hosted release v2.5.0

docs/concepts/worker-pools/kubernetes-workers.md
Related to https://github.com/spacelift-io/kube-workerpool-controller/pull/137
=> doc(CU-8695gnmc0): use server side apply for workerpool controller

docs/concepts/run/README.md
=> Update README.md to add run state NONE information

docs/concepts/run/tracked.md, docs/concepts/spaces/access-control.md
=> Audittrailaccesscontrols

docs/concepts/policy/notification-policy.md
=> note about placeholders only being applicable for pull request comments

docs/integrations/api.md
=> chore: emphasized required JWT token for introspection API

docs/integrations/cloud-providers/aws.md
=> chore: adjust aws principal value in policy examples

docs/vendors/cloudformation/integrating-with-sam.md
With the latest Alpine, Python's packages are externally managed. Let's install AWS CLI tools into a virtual environment.
Ticket: CU-86985fb98
=> fix(sam): adjust pip usage in SAM example

docs/concepts/blueprint/README.md
=> Update blueprint docs to include information about multi stacks

docs/product/administration/install.md
Selfhosted PR: https://github.com/spacelift-io/self-hosted/pull/888
=> feat: documented automatically_report_usage_data param

docs/concepts/stack/stack-dependencies.md
=> fix: image position

docs/concepts/policy/notification-policy.md
=> feat: Document including run logs in webhook notifications

docs/concepts/blueprint/README.md
=> update blueprint schema in docs

docs/concepts/stack/stack-settings.md
Just updating the docs after we added [more items](https://github.com/spacelift-io/backend/pull/9727) to the list of well known secrets.
=> doc(CU-8698cuyfb): add more well known secrets masking

docs/product/administration/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Add selfhosted v2.6.0 changelog

docs/concepts/worker-pools/docker-based-workers.md
=> feat: add deployment options for self-hosted workers using Terraform and CloudFormation

docs/concepts/blueprint/README.md
=> Blueprints include maps documentation

docs/product/administration/advanced-installations.md, docs/product/administration/changelog.md, docs/product/administration/install.md
=> Update selfhosted docs with scheduler

docs/concepts/blueprint/README.md
=> add a section about depedencies to blueprints

docs/concepts/blueprint/README.md
=> fixed spelling and grammar

docs/product/administration/changelog.md
=> Add a changelog entry for Self-Hosted release v2.6.1

docs/concepts/blueprint/README.md
=> Add section about blueprint input validation

docs/concepts/policy/notification-policy.md
=> feat(slack): mention users and groups in the default message

docs/concepts/run/ai.md
=> removing beta warning from saturnhead ai

docs/concepts/worker-pools/docker-based-workers.md
=> Mention AMI updates and deprecation

docs/integrations/observability/datadog.md
=> JSON for the datadog dashboard

docs/integrations/api.md, markdown-link-check.json
So that you don't need to copy it from the picture. :D
=> Add the Github Action issuer in a written form

docs/installing-spacelift/reference-architecture/guides/deploying-to-aks.md
=> chore: bump aks module version

docs/installing-spacelift/changelog.md, docs/installing-spacelift/cloudformation/cloudformation-to-opentofu-terraform-migration.md, docs/installing-spacelift/install-methods.md, nav.self-hosted.yaml
The title could be misleading since v3 could be technically CloudFormation too.
=> Rename "v2 to v3" terminology

docs/integrations/cloud-providers/aws.md
=> make principal info tip for saas only

docs/vendors/pulumi/README.md
=> Pulumi updates

docs/assets/css/custom.css, mkdocs.yaml
=> Adjust dark mode colors

docs/concepts/spaces/access-control.md
=> update space access controls

docs/concepts/configuration/context.md
The [docs on context auto-attachments](https://docs.spacelift.io/concepts/configuration/context.html#auto-attachments) say:
> If you want to attach a context to all projects, you can use the `autoattach:*` label on the context. This will attach the context to all projects, regardless of their labels.
This doesn't explain how `autoattach:*` relates to spaces. If a context is associated with a specific space, `autoattach:*` will only apply to stacks in that space and its child spaces.
This PR will add a sentence explaining how `autoattach:*` works with
spaces.
- Spacelift support ticket 5558 (2025-06-13)
- [Spacelift feedback: Add ability to automatically attach contexts to stacks in owning or inherited spaces](https://feedback.spacelift.io/p/add-ability-to-automatically-attach-contexts-to-s …
=> Document how `autoattach:*` works with spaces

docs/integrations/api-development-with-mcp.md, docs/integrations/api.md, nav.self-hosted.yaml, nav.yaml
- Add new guide showing how to use spacectl's MCP server with AI coding assistants
- No need to learn GraphQL API - assistants discover it automatically via introspection
- Add prominent tip in main API docs directing to MCP approach as quickest way to start
- Organize API docs with traditional and MCP approaches under API section
See the result [here](https://spacelift-user-documentation-pr-820.onrender.com/integrations/api-development-with-mcp.html).
_Spacelift employees should …
=> Add MCP server guide for AI-assisted API development

docs/concepts/stack/stack-dependencies.md, docs/installing-spacelift/changelog.md, docs/vendors/terraform/terraform-provider.md
=> Changelog for SH v3.1.0

docs/concepts/policy/push-policy/README.md
=> add ready state to in cancel list

docs/installing-spacelift/changelog.md, docs/vendors/terraform/terraform-provider.md
=> feat: sh v3.2.0 release

docs/vendors/terraform/module-registry.md
I think this is explicit enough?
=> Module registry change image wording

docs/self-hosted.md
Reflecting the fact that we know support multiple platforms.
=> docs: update self-hosted platform support to include GCP, Azure, and on-premise

docs/legal/terms.md
=> terms and conditions update

docs/concepts/policy/login-policy.md, docs/concepts/worker-pools/README.md
Fixed indentation formatting for login policies member and teams sections. Added info on US regional URLs needed for worker pools AWS services. Changed some admonition types.
=> Update login-policy.md and worker-pools README

docs/integrations/api.md
Updating api key config file in docs to match the app.
=> Update API key config file template

docs/concepts/policy/README.md, docs/concepts/policy/policy-flag-reset.md
Documentation for new reset policy flags feature: https://github.com/spacelift-io/backend/pull/10231
=> Reset policy flags documentation

docs/concepts/worker-pools/docker-based-workers.md
Technically it didn't have any problems, I just wanted to add the sensitive output uploads, as well as fixing another small thing.
=> Update Worker Pool module code snippet

docs/concepts/policy/push-policy/run-external-dependencies.md
=> Allow dependencies to be skipped

docs/concepts/worker-pools/docker-based-workers.md, docs/installing-spacelift/reference-architecture/guides/deploying-to-ecs.md
A small project I worked on this week.
=> Add information about spot instances

docs/installing-spacelift/reference-architecture/guides/observability.md, docs/installing-spacelift/reference-architecture/reference/message-queues.md
Additional info about scaling the drain.
=> Extend message queue docs with scaling

docs/installing-spacelift/changelog.md
=> Add message queue config addition to the changelog

.vscode/settings.json, docs/product/fedramp.md, nav.yaml
=> Add FedRAMP page

.github/workflows/qa.yaml
No QA validation needed for claude config.
=> Ignore CLAUDE.md when determining changed files

docs/installing-spacelift/changelog.md, docs/product/changelog.md, nav.yaml, scripts/remove-files-based-on-distribution.sh
As part of our agreement, let's start to maintain changelogs.
=> Start the SaaS changelog

docs/installing-spacelift/changelog.md
Update self hosted changelog for version 3.5.0 with policy samples info
=> Add policy samples to 3.5.0 self hosted version features list

docs/product/fedramp.md
=> Add link to the FedRAMP Marketplace listing

docs/concepts/worker-pools/kubernetes-workers.md
=> fix: lowercase in example

docs/installing-spacelift/cloudformation/disaster-recovery.md
ICE was asking for this information, it wasn't super obvious.
=> Small updates to the DR docs
