- docs/concepts/worker-pools.md
We download our public PGP key from keys.openpgp.org. This is used to verify the signature of the worker binary downloaded by the launcher.
> Document worker requirement on PGP

- docs/concepts/stack/stack-settings.md
Remove outdated section about persisting env vars
Preview link: https://spacelift-user-documentation-pr-101.onrender.com/concepts/stack/stack-settings.html#customizing-workflow
> Remove outdated section about persisting env vars

- docs/concepts/policy/git-push-policy.md
It looks like the `message` example in the Git Push policy is incorrectly using parenthesis instead of curly brackets.
```opa
message["I love bacon"] ( true )
```
This results in the following error:
```none
error occurred: policy.rego:4: rego_parse_error: boolean cannot be used for rule name
```
Replacing `( true )` with `{ true }` makes the expression a valid rule.
> Fix message example in Push policy docs

- docs/vendors/terraform/module-registry.md
Fixed a few small typos on the module registry docs, and updated the section on policies to explain that trigger policies can actually be used with modules to automatically trigger consumers, and removed the part about tasks. I figured it's self-explanatory that task policies don't apply since modules don't have tasks.
> Fixes for the module registry docs

- docs/integrations/cloud-providers/azure.md
While taking a look at the docs I noticed that the Azure page says that the managed integration can only be used on public workers, which isn't true.
> Azure managed integration can be used on public workers

- docs/integrations/source-control/bitbucket-datacenter-server.md
I've moved the screenshot showing the webhooks URL and secret into the "Configuring webhooks" section. Previously it was a little confusing when sending a direct link to someone because they wouldn't have the context of where to get this information.
> Show BBDC webhooks screenshot in webhooks section

- docs/concepts/policy/notification-policy.md
I changed the wording from "can" to "you will need to" because "can" seemed like it was optional, however if you do not configure it that way, it will result in a status code 400
> changes wording

- docs/concepts/configuration/context.md
- docs/vendors/terraform/module-registry.md
Changing stacks to contexts in the module environment description - I think this is a typo 🙌 
Also noticed the same mistake in Context docs.
> Fix module registry env typo

- overrides/partials/banner.html
By default, all the CTA URLs from top banner shouldn't have `nofollow` attribute, and we need the ability to decide when we want to add it. 
> add nofollow rel to banner link

- docs/assets/css/extra.css
- hooks/fetch_banner.py
- overrides/partials/banner.html
The current banner is aligned across the website and docs. If we edit the message to promote our attendance at an event, for example, that is not relevant for docs, we want to separate the functionality, so we can update the website without updating docs (or vice versa).
Secondly, add support for `color` prop.
> change source for top banner

- .github/pull_request_template.md
We need to temporarily disable the Render previews, so I'm removing it from the checklist to avoid confusion.
> Temporarily remove preview from PR checklist

- docs/concepts/blueprint/README.md
- docs/integrations/api.md
- docs/self-hosted.md
- docs/vendors/terraform/module-registry.md
- docs/vendors/terraform/provider-registry.md
- main.py
- markdown-link-check.json
- mkdocs.yaml
- nav.self-hosted.yaml
- requirements.txt
This PR doesn't actually add any self-hosted docs to the repo, but it adds the following things:
- [Mike](https://github.com/jimporter/mike) - an MkDocs plugin that allows multiple versions of documentation to be published.
- [MkDocs Macros](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) - allows us to use templates within documentation.
- A separate nav file for self-hosted.
I'll post further PRs with things like updates to the Render and GitHub Actions pipelines, along with docs explaining how to work on the self-hosted docs.
If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull …
> Add self-hosted docs support with Mike

- .github/workflows/deploy-to-environment.yaml
- .github/workflows/workflow.yaml
- scripts/render-build.sh
- Updated the GitHub Actions workflow to deploy the self-hosted docs. At the moment we'll only deploy to preprod.
- Added a script we can call from Render to build a copy of the docs containing the latest version of both SaaS and self-hosted docs.
I've also temporarily pushed a version of the docs to a branch called `self-hosted-releases`. This is to allow us to test the workflow, but we can completely delete and recreate before releasing after making any required changes to the docs.
_Spacelift employees should request reviews from …
> Update builds for self-hosted

- .github/workflows/self-hosted-release.yaml
- .github/workflows/workflow.yaml
This new workflow allows us to tag the repo with a tag in the format `self-hosted-vx.y.z` to automatically publish a new version of the self-hosted documentation. This will run Mike, push the changes to the `self-hosted-releases` branch, and then trigger deployments.
For now I've left the production deploy commented out because I don't want to accidentally deploy to prod until we're happy.
I've also added concurrency groups to both the self-hosted release workflow and the main deployment workflow to avoid a situation where both attempt to deploy changes at the same time.
If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone …
> Add self-hosted release workflow

- .vscode/tasks.json
- CONTRIBUTING.md
The preview commands were broken because of the new mkdocs plugins that have been added. I've updated the commands to just use the `python` Docker image. This means we can install the correct dependencies via the requirements.txt file, although it does make the commands pretty verbose.
> Fix the preview commands

- docs/integrations/source-control/gitlab.md
GitLab: fix link pointing to stack creation description
> GitLab: fix link pointing to stack creation description

- docs/self-hosted.md
The link to the self-hosted install guide is broken because of the way our Lambda that adjusts URLs works. It needs the trailing slash removed to work.
> Fix the link to the install guide

- v0.0.7/product/support/index.html
Updating the v0.0.7 snapshot of the self-hosted docs to mention the support email.
> Mention support email in v0.0.7 docs

- .github/workflows/self-hosted-release.yaml
- scripts/render-build.sh
The current version of the self-hosted docs build wasn't specifying the `DOC_ENV` flag. This meant that we were using the development configuration for things like analytics.
To solve what I've done is created two Mike builds - one for preprod and another for prod. They publish to two separate branches: `self-hosted-releases-preprod` and `self-hosted-releases-prod`. I haven't updated the main workflow yet to use those branches, and I've also disabled the deploy on the self-hosted-release workflow because we need the branches to be created before we can use them. I'll update the workflows in a separate PR.
If the proposed change is ready to be merged, please request a review from …
> Build separate preprod/prod copies of self-hosted

- .github/workflows/deploy-to-environment.yaml
- .github/workflows/self-hosted-release.yaml
- Updated the deployment workflow to get the self-hosted docs from the correct branch depending on the environment being deployed.
- Updated the self-hosted release process to trigger a deploy again.
> Deploy self-hosted docs from correct branch

- .github/workflows/self-hosted-release.yaml
It means that if someone goes to https://docs.spacelift.io/self-hosted/latest/self-hosted they'll get a 404 instead of getting a page with broken links.
> Remove self-hosted.md from self-hosted docs

- docs/concepts/policy/login-policy.md
Added an info panel to let the reader know that the login policy is not evaluated on the free tier. 
> add panel to say Login Policy is not on Free Tier

- mkdocs.yaml
- requirements.txt
It looks like during adding [external dependencies docs](https://github.com/spacelift-io/user-documentation/commit/8d38961a646053f566fcaeea7ebd17b033b66e75#diff-8bd4b3e7221bce03a74d78a5a2ba5c43327621cf8ddc583c111a15ed619b24ac) we moved `git-push-policies` to just `push-policies` which is fine, but we should add some redirects just in case we linked to git-push-policies page somewhere before. 
_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one …
> Add push policy redirect

- docs/concepts/worker-pools.md
Adding documentation for the new parameter added to the Self-Hosted CloudFormation worker pool stack that allows the launcher to run as either the `spacelift` user or `root`.
> Document RunLauncherAsSpaceliftUser

- v0.0.7/concepts/worker-pools.html
The ability to specify custom commands won't exist until the v0.0.8 release, so let's remove that from the v0.0.7 docs. The problem is that this feature was implemented while we were adding the Self-Hosted docs to the site, so it ended up in here by accident.
> Remove custom command injection from CF stack

- docs/concepts/stack/stack-dependencies.md
- docs/concepts/stack/stack-settings.md
Add `stack_destructor` resource information to `*_destroy` hooks.
> Add stack_destructor_resource to destroy_hooks

- docs/product/administration/install.md
Updated the Self-Hosted upgrade notes to also mention deploying the latest version of the Cloudformation worker pool template. While this isn't strictly necessary, it's possible we may have included fixes to the worker pool template as part of a release.
> Mention upgrade CF workers template when upgrading

- docs/vendors/terraform/terragrunt.md
This adds a notice to the current terraform+terragrunt docs page to point to the new beta page.
> Added notice to tf+tg page to notify users of the new terragrunt beta

- docs/concepts/worker-pools.md
- docs/vendors/kubernetes/helm.md
I've updated the references to the Helm Chart repository since the repository name is changed after publishing the VCS Agent Helm chart in the same repository.
> Updated references for the Helm Chart repo to new URL and repo name

- docs/vendors/terragrunt/reference.md
A new environment variable (`TG_CLI_ARGS_init`) is now supported to allow for setting env vars during the init phase too.
> added new environment variable documentation for terragrunt backends

- docs/integrations/source-control/github.md
Documenting how to enable git checkout support for an individual stack/module. At the moment the stack label is only supported for GitHub (both managed and custom App), so I've added it to the GitHub section of the docs.
> Add documentation on enabling git checkout support

- docs/integrations/source-control/github.md
The magic label for Git checkout preview is actually different.
> Fix broken label

- .github/workflows/self-hosted-release.yaml
- mkdocs.yaml
- scripts/render-build.sh
Fix canonical links for self hosted docs to match URLs
> Fix canonical links for self-hosted docs

- docs/concepts/worker-pools.md
I've added information about Server-side initialization policy deprecation in the Worker Pool configuration docs.
> Added a warning about Server-side initialization policy deprecation

- docs/vendors/terraform/terraform-provider.md
I've added some information explaining that the latest TF provider may not always be compatible with Self-Hosted versions, recommended pinning to a known compatible version, and added a version compatibility matrix.
I haven't gone through and back-filled previous versions, but we can add to this going forward.
Thank you for your …
> Add Self-Hosted TF provider compatibility info

- docs/concepts/policy/terraform-plan-policy.md
We got some feedback that the previous run field is missing in the plan policy schema documentation. It's kind of tricky, because it will be missing for the first run indeed.
> Add previous run meta to plan policy along with a note

- docs/concepts/worker-pools.md
Added the configuration option for SPACELIFT_DEBUG to the worker pool documentation page. 
> added definition for SPACELIFT_DEBUG

- docs/assets/css/extra.css
- overrides/partials/header.html
This PR is fixing the sidebars css issue introduced by top banner:
https://github.com/spacelift-io/user-documentation/assets/7979992/2deeb7f7-85f4-408d-b061-9f227aa23a65
> Fix banner styles

- docs/vendors/kubernetes/getting-started.md
> adding reference to format of kubectl timeout variable

- docs/vendors/terraform/provider-registry.md
Added warning blocks to the Provider Registry documentation about the `type` and `version ID` attributes.
> Added warnings to the provider registry docs

- docs/concepts/worker-pools.md
- docs/integrations/docker.md
I bumped into this issue where 2 customers didn't know any of this.
> Adding two notes about workerpools and docker images

- docs/integrations/cloud-providers/oidc/gcp-oidc.md
I've added a warning block to the GCP OIDC configuration documentation about exceeding threshold situations. 
> Added a warning to the GCP OIDC doc

- docs/concepts/blueprint/README.md
A prospect reported that after reading the introduction to the Blueprints page, they thought it was meant for temporary stacks. This PR clarifies the use case for this feature.
> Clarify the motivation for using blueprints

- docs/integrations/cloud-providers/oidc/gcp-oidc.md
- The `audience` parameter in the credential config file needs to use the project number, not the project ID.
- I've tweaked the part about configuring the Terraform provider to explicitly mention setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. From testing, service account impersonation doesn't work correctly if you use other options like setting the `credentials` property in a provider configuration block.
_Spacelift employees should request reviews from the …
> Clarify a couple of points in the GCP OIDC docs

- docs/concepts/worker-pools.md
Updated the CRD API versions to v1beta1 to match the versions of the Kubernetes Operator's latest version.
> Updated API version to v1beta1 for the Kubernetes Operator docs

- docs/concepts/worker-pools.md
I've added an example showing how to configure a Kubernetes WorkerPool alongside a VCS Agent.
> Document how to use VCS Agents with k8s workers

- docs/product/administration/changelog.md
I've added a note to mention that the Kubernetes operator is officially supported in Self-Hosted from v1.0.0.
> Mention Kubernetes workers in Self-Hosted changelog

- docs/concepts/policy/notification-policy.md
Added pull request notification placeholders for initializing and preparing run phases.
> Additional pull request placeholders

- docs/concepts/worker-pools.md
I've added a section to clarify that billing for Kubernetes workers is identical to how our other workers are billed, and that a worker counts towards your usage even when idle.
> Clarify how billing works for Kubernetes workers

- docs/concepts/configuration/context.md
- docs/concepts/stack/creating-a-stack.md
- docs/concepts/stack/stack-dependencies.md
- docs/faq/README.md
- docs/vendors/terraform/module-registry.md
This PR fixes a few links that pointed to index files, but were missing `README.md` which is required by MkDocs.
> Add missing README.md to index links

- docs/concepts/worker-pools.md
Added a section to clarify that a new Pod is created per run, and that this can cause problems with systems that use Pod labels to determine identity since each run Pod has a different set of labels.
> Add a troubleshooting note about pod network identity

- docs/concepts/worker-pools.md
Adds more info in the `WorkerPool` CRD doc to show required and optional fields.
> doc: add required/optional fields for WorkerPool CRD

- docs/concepts/worker-pools.md
I've tried to improve the docs about how to configure the binaries cache and workspace volumes for Kubernetes workers. I've removed the text that recommended configuring these volumes for production, and instead tried to explain reasons that you might want to configure them to allow users to make their own decisions.
I've also added an example showing how to configure a worker pool using GP2 storage for the workspace volume.
_Spacelift employees should request reviews from the …
> Improve documentation about k8s volume configuration

- docs/concepts/configuration/README.md
- docs/concepts/configuration/runtime-configuration/README.md
We've added a v2 version of the config.yml file that brings the stack runtime config in line with the runtime config used for module tests cases, and grants stack defaults higher precedence than the current stack settings. This makes it possible to change settings across all stacks in one place, but is opt-in (via the version) for backwards compatibility.
_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at …
> Document change in precedence rules between config versions

- docs/vendors/terragrunt/reference.md
Let's make it clearer: what does it mean if we don't specify terraform/terragrunt version?
> Terragrunt OpenTofu: Make it clear that defaulting to latest version in TF provider only applies on creation

- docs/concepts/policy/task-run-policy.md
https://play.openpolicyagent.org/p/MPoP9yQpEp
https://www.openpolicyagent.org/docs/v0.22.0/policy-reference/
https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-regex-regexmatch
> Update task-run-policy.md deprecated re_match to regex.match

- .github/workflows/deploy-to-environment.yaml
- .github/workflows/qa.yaml
- .github/workflows/self-hosted-release.yaml
Fixes GitHub Actions workflow warnings:
> Fix GitHub Actions workflow warnings

- .editorconfig
- hooks/move_index.py
- mkdocs.yaml
Move files so that urls ending/not ending with / dont break.
This adds a hook to `mkdocs` that makes the following changes:
`README.md` -> `/index.html`
`/files/in/directories/README.md` -> `/files/in/directories.html`
When combined with the infrastructure change, this should fix the issue with broken links because of missing slashes. …
> feat: move files so that we dont break links on accident

- CONTRIBUTING.md
Latest published version of the `videah/oxipng` docker image is 2 years old and it's using `7.0.0`. The latest published version is `9.1.1`. Our pipeline uses a more recent version than `7.0.0` which causes the linter to throw an error.
> Update tip for running oxipng locally

- docs/integrations/api.md
> changing http method to https

- docs/product/administration/install.md
> Adjust docs for DR self-hosted

- docs/concepts/stack/stack-settings.md
I was initially confused on how the autoattach labels work - the docs were a bit not clear whether I should add `autoattach:label` on the stack side or just the `label`. Hoping this change makes it a bit more clear
> Reword autoattach labels description to be a bit more obvious

- docs/product/administration/install.md
I've added documentation for the new `webhooks_endpoint` option that will be released in the next version of Self-Hosted.
> Document Self-Hosted webhooks_endpoint option

- docs/concepts/worker-pools/README.md
I've updated the worker network security section to mention our new worker endpoint (`worker-iot.spacelift.io`), and to also explain that the AWS services in multiple regions need to be allowed in case of a DR failover.
> Update worker network requirements for DR changes

- docs/product/administration/install.md
I've added documentation about how to use a custom domain for the IoT broker.
> Document IoT broker endpoint

- docs/concepts/policy/push-policy/run-external-dependencies.md
- docs/concepts/spacectl.md
- docs/integrations/api.md
- docs/vendors/terraform/provider-registry.md
Remove `GITHUB_TOKEN` from `setup-spacectl` calls as it isn't required anymore
> Remove `GITHUB_TOKEN` from `setup-spacectl` calls as it isn't required anymore

- docs/concepts/worker-pools/kubernetes-workers.md
> docs(concepts/worker-pools/kubernetes-workers): explain proper formatting for wp_token and wp_private_key

- docs/vendors/ansible/reference.md
- docs/vendors/terraform/external-modules.md
> adds warning note and fixes small typo

- docs/integrations/chatops/slack.md
[At the bottom of our documentation](https://docs.spacelift.io/integrations/chatops/slack.html#available-slash-commands) for slack we say "Available Slash Commands", then there is little message that says:
>It's recommended to instead use the [notification policy](https://docs.spacelift.io/concepts/policy/notification-policy) in order to manage slack messages received from Spacelift. These slash commands are deprecated.
After that it says:
> Three slash commands are currently available:
> /spacelift subscribe $stackId - subscribes a particular Slack channel to run state changes for a given Stack - requires ;
> /spacelift unsubscribe $stackId - unsubscribes a particular Slack channel from run state changes for a given Stack;
> /spacelift trigger $stackId - triggers a tracked run for the …
> Edited Slack Docs

- docs/integrations/cloud-providers/oidc/aws-oidc.md
- docs/integrations/cloud-providers/oidc/azure-oidc.md
- docs/integrations/cloud-providers/oidc/vault-oidc.md
Our OIDC subpages (AWS, Azure, Vault) currently lack reminders that OIDC integrations are only available for paid Spacelift accounts. Some documentation links bypass the parent OIDC page, which includes this important information, leading users to potentially miss that these features require a paid account.
Thank you for your …
> Added hint box to OIDC pages

- docs/vendors/cloudformation/README.md
- docs/vendors/cloudformation/getting-started.md
Currently the CloudFormation integration can't upload templates to S3 buckets containing `.`. I've added a section to the CloudFormation docs explaining this along with a callout in the getting started guide.
> Explain restriction with CloudFormation S3 bucket names

- docs/vendors/terraform/module-registry.md
Cannot merge this until the latest version of the OpenTofu provider is released.
> docs(vendors/terraform/module-registry): mention people can make modules public

- docs/concepts/worker-pools/kubernetes-workers.md
I want to highlight that setting very low Kubernetes CPU or memory limits can cause performance issues when executing runs. I've also commented out the limits by default in the examples to make it less likely they are blindly copied and used without being adjusted.
> Make it more obvious that k8s resource limits can cause run failures

- docs/vendors/terraform/state-management.md
Fixing a typo to correctly use rel=nofollow
> Fix a typo in state-management.md

- docs/concepts/user-management/admin.md
> fix(user-management): remove mention about user invitations codes

- docs/concepts/policy/approval-policy.md
- docs/concepts/policy/login-policy.md
- docs/concepts/policy/push-policy/README.md
- docs/concepts/policy/stack-access-policy.md
- docs/concepts/policy/terraform-plan-policy.md
- docs/concepts/policy/trigger-policy.md
- docs/integrations/source-control/github.md
When I was setting the github integration manually it was a bit annoying that the last permission was not in the alphabetical order (I had to scroll back to set it), other than that all of the permissions were in the order they appear in github so it was much easier to follow. 
> Sort permissions to set alphabetically so it's easier to follow

- docs/vendors/terraform/provider-registry.md
Remove spacelift.io hostname for the SH tf provider code snippet 
> fix using tf providers for sh

- docs/concepts/stack/stack-dependencies.md
> adding note regarding imported outputs

- docs/concepts/worker-pools/kubernetes-workers.md
This adds a section to explain how to use the workerpool controller metrics.
I also make the warning a bit more visible in the Helm installation section, and fixed indentation for the promex exporter.
> doc(CU-869756wtw): add a section about workerpool controller metrics

- docs/product/administration/slack-integration-setup.md
> notes to change the slack integration and remove it

- docs/concepts/worker-pools/kubernetes-workers.md
This fixes feedback from @Apollorion where using Helm chart the controller version in use is maybe not explicit enough.
>  I think the only nitpicky thing that I'd mention is that our chart versions and app versions dont align so when we link to the Upgrading to 0.0.17 section of the docs in the release notes its a little confusing because we released 0.33.0 of the chart.
Maybe we make the title of that section Upgrading to app 0.0.17/Chart 0.33.0 or something along those lines. …
> doc: make upgrade version more explicit

- docs/concepts/run/ignored-triggers.md
> Change triggers to warnings

- docs/concepts/policy/README.md
Adding hint about prepended variable definitions for the policies. One of the customers ran into conflict errors related to them and we want to give a better explanation what's happening behind the scene.
Here's a corresponding [PR for the policy templates](https://github.com/spacelift-io/frontend/pull/5249)
Here's the outcome:
Thank you …
> docs: add hint about prepended variable definitions for the policies

- docs/concepts/worker-pools/kubernetes-workers.md
I've updated the configuration section and added an example of how to use `customBinariesPath`.
> Document the customBinariesPath option for k8s workers

- CONTRIBUTING.md
- Dockerfile
- Makefile
- docker-compose.yml
I got bored of finding the docker run command in my shell history, so let's instrument docs preview a bit better.
> feat: add `make run` using docker

- docs/integrations/teleport.md
model
We've updated the Teleport Terraform Provider to remove the necessity of the `teleport-spacelift-runner` custom docker image, this is simpler for users & removes our need to maintain an image tracking the Spacelift base docker image.
This PR updates the documentation to leverage the new functionality within the Teleport Terraform Provider and removes the steps to setup the `teleport-spacelift-runner` image.
Related to https://github.com/gravitational/teleport/issues/46425 …
> Update Teleport integration documentation

- docs/integrations/cloud-providers/oidc/README.md
I've moved the explanation about needing the Spacelift server instance to be accessible by the service provider you are trying to connect to into its own section instead of a note at the top of the page. I've also detailed the URLs used, along with explaining that some providers may support manually uploading the keys.
Thank you for your …
> Clarify that OIDC Federation requires access to Spacelift server instance

- docs/concepts/configuration/runtime-configuration/README.md
https://github.com/spacelift-io/terraform-provider-spacelift/issues/540#issuecomment-2137455063
The customer suggested that it's not obvious `terragrunt` block isn't applied for different (Terraform, Ansible... ) stack types.
Especially, it makes sense for monorepos, where we could mix different configurations.
Thank you for your …
> fix: let's specify how terragrunt block works in case stack isn't terragrunt

- docs/concepts/policy/notification-policy.md
Updates notification policy data input documentation to include Ansible specific changes objects.
Part of: https://github.com/spacelift-io/backend/pull/10815
> chore: update Ansible specific notif data input docs

- docs/concepts/authorization/README.md
- docs/concepts/authorization/assigning-roles-api-keys.md
- docs/concepts/authorization/assigning-roles-groups.md
- docs/concepts/authorization/assigning-roles-users.md
- docs/concepts/authorization/rbac-system.md
- docs/concepts/policy/login-policy.md
- docs/concepts/spaces/access-control.md
- docs/concepts/user-management/README.md
- docs/installing-spacelift/changelog.md
- nav.yaml
> docs(aac): initial updates to authorization docs

- docs/concepts/policy/notification-policy.md
While I can see who these links can potentially make sense, they are not broken and would take a while to fix, then when we'd change inputs, we'd need to remember to update these as well, which we will never do. Thats why I propose to just remove tem.
> Remove broken links to rego playground

- docs/concepts/worker-pools/kubernetes-workers.md
Add documentation for successfulPodsHistoryLimit, failedPodsHistoryLimit, successfulPodsHistoryTTL, and failedPodsHistoryTTL fields. Include examples for different cleanup modes and clarify that limits apply per worker
> chore: update Kubernetes workers for new pod history management

- docs/concepts/worker-pools/kubernetes-workers.md
Updates helm chart version in pod history cleanup notice for keepSuccesfulPods deprication to use chart version and not the app version that's inside the chart.
> fix: update helm chart version in pod history cleanup notice

- nav.self-hosted.yaml
- nav.yaml
https://docs.spacelift.io/self-hosted/latest/sitemap.xml
vcs agent pool is not showing in the sitemap.
trying to figure out why.
> Move VCS agent pools navigation location
